name: CI-MLflow-Training-Docker

on:
  push:
    branches:
      - main

jobs:
  train-and-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install mlflow scikit-learn pandas numpy dagshub

    - name: Run MLflow Training
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/david123410/Eksperimen_SML_David.mlflow
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        cd MLProject
        python modelling.py

    - name: Upload run_id artifact
      uses: actions/upload-artifact@v4
      with:
        name: run-id
        path: MLProject/run_id.txt

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image with MLflow
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/<USERNAME>/<REPO>.mlflow
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        RUN_ID=$(cat MLProject/run_id.txt)
        mlflow models build-docker \
          -m runs:/${RUN_ID}/model \
          -n ${{ secrets.DOCKER_USERNAME }}/gender-classification-mlflow

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/gender-classification-mlflow
